name: CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x ./gradlew
          ./gradlew jar
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: joinreqbot
          path: build/libs/*.jar
        
